In [1]:
import numpy as np
import pandas as pd

weather = pd.read_csv('./weather_Final.csv')
weather.head()

,Unnamed: 0,Year,Month,day,temp_max,temp_avg,temp_min,dewp_max,dewp_avg,dewp_min,...,wind_max,wind_avg,wind_min,pres_max,pres_avg,pres_min,prec,Time,DTR,weather
0,732,2019,1,1,63,57.8,51,59,54.4,50,...,8,3.6,0,29.5,29.5,29.4,1.09,2019-1-1,12,Drizzle
1,733,2019,1,2,53,50.6,48,51,49.0,48,...,9,4.5,0,29.6,29.5,29.4,0.00,2019-1-2,5,Cloudy
2,734,2019,1,3,55,52.1,50,54,50.4,48,...,14,5.5,0,29.4,29.3,29.2,0.56,2019-1-3,5,Drizzle
3,735,2019,1,4,62,52.6,43,59,48.4,40,...,23,13.6,6,29.3,29.1,29.0,0.82,2019-1-4,19,Rain
4,736,2019,1,5,60,45.9,40,40,38.1,35,...,16,7.2,0,29.5,29.4,29.3,0.01,2019-1-5,20,Sun

In [4]:
import scipy.stats as stats
data = pd.DataFrame(weather, columns=['temp_max', 'temp_avg', 'temp_min','dewp_max','dewp_min','pres_max','pres_min','pres_avg','prec','DTR'])
data.apply(stats.zscore)

,temp_max,temp_avg,temp_min,dewp_max,dewp_min,pres_max,pres_min,pres_avg,prec,DTR
0,-0.839946,-0.498015,-0.248761,0.051158,0.154011,0.192862,0.120519,0.624812,1.969296,-0.857951
1,-1.555557,-1.012066,-0.434781,-0.524436,0.039430,0.895751,0.120519,0.624812,-0.369918,-1.635320
2,-1.412435,-0.904972,-0.310768,-0.308588,0.039430,-0.510027,0.048880,-0.511869,0.831880,-1.635320
3,-0.911507,-0.869274,-0.744814,0.051158,-0.418897,-1.212916,-0.022759,-1.648550,1.389857,-0.080582
4,-1.054629,-1.347627,-0.930834,-1.315877,-0.705351,0.192862,0.084700,0.056471,-0.348457,0.030471
...,...,...,...,...,...,...,...,...,...,...
1092,-0.052774,0.280202,0.619331,0.410904,0.784210,-0.510027,0.048880,-0.511869,-0.369918,-1.191109
1093,0.090348,0.337318,0.557325,0.698701,0.898792,-1.915805,0.013061,-1.080210,-0.369918,-0.857951
1094,0.161909,0.430133,0.681338,0.842600,0.898792,-1.915805,0.013061,-1.080210,-0.369918,-0.969004
1095,0.018787,0.073153,0.061272,0.770650,0.497756,-1.212916,0.048880,-1.080210,-0.369918,-0.080582
1096,-0.195896,0.430133,0.929365,0.770650,1.185246,-1.915805,0.048880,-1.080210,-0.369918,-1.968478

In [6]:
weather

,Unnamed: 0,Year,Month,day,temp_max,temp_avg,temp_min,dewp_max,dewp_avg,dewp_min,...,wind_max,wind_avg,wind_min,pres_max,pres_avg,pres_min,prec,Time,DTR,weather
0,732,2019,1,1,63,57.8,51,59,54.4,50,...,8,3.6,0,29.5,29.5,29.4,1.09,2019-1-1,12,Drizzle
1,733,2019,1,2,53,50.6,48,51,49.0,48,...,9,4.5,0,29.6,29.5,29.4,0.00,2019-1-2,5,Cloudy
2,734,2019,1,3,55,52.1,50,54,50.4,48,...,14,5.5,0,29.4,29.3,29.2,0.56,2019-1-3,5,Drizzle
3,735,2019,1,4,62,52.6,43,59,48.4,40,...,23,13.6,6,29.3,29.1,29.0,0.82,2019-1-4,19,Rain
4,736,2019,1,5,60,45.9,40,40,38.1,35,...,16,7.2,0,29.5,29.4,29.3,0.01,2019-1-5,20,Sun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,362,2021,12,27,74,68.7,65,64,63.2,61,...,18,10.8,5,29.4,29.3,29.2,0.00,2021-12-27,9,Sun
1093,363,2021,12,28,76,69.5,64,68,65.2,63,...,18,12.2,3,29.2,29.2,29.1,0.00,2021-12-28,12,Sun
1094,364,2021,12,29,77,70.8,66,70,66.8,63,...,17,11.5,3,29.2,29.2,29.1,0.00,2021-12-29,11,Sun
1095,365,2021,12,30,75,65.8,56,69,65.1,56,...,7,2.7,0,29.3,29.2,29.2,0.00,2021-12-30,19,Cloudy
1096,366,2021,12,31,72,70.8,70,69,68.5,68,...,18,9.5,6,29.2,29.2,29.2,0.00,2021-12-31,2,Sun